spring:
  application:
    name: sharging-jdbc-demo
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: master,slave1
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://192.168.100.130:5500/db_test
        username: postgres
        password: postgress@123
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://192.168.100.130:5501/db_test
        username: postgres
        password: postgress@123
    rules:
      readwrite-splitting:
        data-sources:
          # 数据源的逻辑名称
          myds:
            type: Static
            props:
              # 写数据源的名称
              write-data-source-name: master
              # 读数据源的名称, 多个以,分割 slave1,slave2
              read-data-source-names: slave1
        # 当前负载均衡算法名称, 可以根据下面的load-balancers选择具体的负载均衡算法
        load-balancer-name: alg_round
        load-balancers:
          # 负载均衡算法类型 alg_round = 轮训
          # alg_round = 轮训
          alg_round:
            type: ROUND_ROBIN
          # 随机算法
          alg_random:
            type: RANDOM
          # 权重算法
          alg_weight:
            type: WEIGHT
            props:
              slave1: 1
logging:
  level:
    com.zaxxer.hikari: WARN
